Feat: Design Network and Add Configuration of Network Component
kookmin-sw/capstone-2021-8 pull request #14
Opened 2021-04-03 11:11 UTC by hughugh

노드 크기, 간격, 글자 크기 등을 조절하고, 추가로 받는 데이터 구조를 변경, configuration 형태로 조절, 글자 넘기기 등을 구현함.
데이터는 인터넷 참조하여 알고리즘, 데이터 구조 등을 참고하여 만들었음.
노드 색상은 여러 가지 적용 해보다가 그 중 괜찮은 것을 선택한 것. 논의가 필요할 듯.

2021-04-04 13:32 UTC, tykim75 approved these changes
![tmp](https://user-images.githubusercontent.com/49232768/113510309-32360980-9595-11eb-9051-090ccfa9e9c8.PNG)
노드 크기, 글자 크기, 툴팁 구현하신 것은 보기에 괜찮은 것 같습니다. 그런데 회색 노드에 하얀 글씨는 가독성이 좀 떨어지는 것 같은데 노드 색상을 연한 파란색 계열로 변경하는게 어떨까 싶습니다.

2021-04-05 05:58 UTC, c0510gy requested changes

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/components/Network/Tooltip/index.js
> +const App = ({ tooltipRef }) => (
change the name of the functional component to something like `NetworkTooltip` from `App`

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/components/Network/index.js
> +const MyResponsiveNetwork = ({ data, handleTooltipInfo }) => (
remove `My` from the name of the component

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/pages/KeywordNetwork/index.js
>  const App = () => {
change the name of the component

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/pages/KeywordNetwork/index.js
> +  let j;
is there any reason to put `i`, `j` here? if there's no reason, remove line 55, 56

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/pages/KeywordNetwork/index.js
> +      for (j = 0; j < data.nodes[i].length; j += 1) {
use `data.nodes.map( (item) => {} )` instead of `for` loops as possible.

same issue for the following lines

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/components/Network/CustomNode/index.js
>  import styles from './Styles.module.scss';
change the name of the scss file to `DesktopDefault.module.scss`

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/components/Network/Tooltip/index.js
> +import styles from './Styles.module.scss';
change the name of the scss file to `DesktopDefault.module.scss`

2021-04-05 05:58 UTC, c0510gy commented on client/paperflow-web-v1/src/pages/KeywordNetwork/index.js
>  import styles from './Styles.module.scss';
change the name of the scss file to `DesktopDefault.module.scss`

2021-04-05 13:12 UTC, c0510gy requested changes

2021-04-05 13:12 UTC, c0510gy commented on client/paperflow-web-v1/src/components/Network/Tooltip/DesktopDefault.module.scss
> +@import '../../../assets//scsses//config';
correct `//` to `/`

2021-04-05 13:12 UTC, c0510gy commented on client/paperflow-web-v1/src/pages/KeywordNetwork/index.js
> +            .attr('transform', 'translate(0,0) scale(1)');
remove extra spaces

2021-04-06 00:13 UTC, hughugh commented on client/paperflow-web-v1/src/pages/KeywordNetwork/index.js
> +            .attr('transform', 'translate(0,0) scale(1)');
저 코드가 아니라 그 바로 위 주석이 한 탭 들어가 있었네요. 수정했습니다.

2021-04-06 00:29 UTC, c0510gy approved these changes

2021-04-06 01:02 UTC, merged