insert arxiv data to mysql
kookmin-sw/capstone-2021-8 pull request #19
Opened 2021-04-18 11:27 UTC by tykim75

- 민종님께서 수집하신 arxiv 데이터를 RDBMS 형식에 맞게 PaperInfo, AuthorsInfo, AbstratInfo, ThemeInfo 라는 네 가지 테이블로 나눔.
- mysql에 모델 정의 및 DB에 데이터 구축 완료

2021-04-18 17:56 UTC, hughugh commented on server/paperflow-functions-v1/paperflowServer/arxiv/models.py
> +    publicationMonth = models.CharField(max_length=2)
현재 camel case와 underscore를 같이 사용하는데, 깔끔하게 underscore로 통일하는게 어떨까 싶습니다.

2021-04-18 17:58 UTC, hughugh commented on server/paperflow-functions-v1/paperflowServer/arxiv/models.py
> +    paperID = models.ForeignKey('PaperInfo', on_delete=models.CASCADE)
참조하여 가져오기 편하도록 related_name을 붙여주시면 좋을 것 같습니다. (예 : authors, abstract)

2021-04-20 12:56 UTC, c0510gy approved these changes
일단은 민종님이 남긴 리뷰만 반영하면 될 것 같습니다.

2021-04-22 00:31 UTC, hughugh requested changes

2021-04-22 00:31 UTC, hughugh commented on server/paperflow-functions-v1/paperflowServer/arxiv/models.py
> +    paperID = models.IntegerField(primary_key=True)
이 paperID를 paper_id로 바꾸시고,
다른 subclass들은 paper 객체 자체를 가리키기 때문에 paper_id가 붙을 이유가 없고, 그냥 변수 이름은 paper라고만 해주셔도 될 것 같습니다. 그리고 부탁드린 related_name이 안붙었는데, [이거](https://fabl1106.github.io/django/2019/05/27/Django-26.-%EC%9E%A5%EA%B3%A0-related_name-%EC%84%A4%EC%A0%95%EB%B0%A9%EB%B2%95.html) 같이 보시고 모든 subclass에 적용부탁드립니다.
abstract로 예를 들면, paper = models.ForeignKey('PaperInfo', on_delete=models.CASCADE, related_name='abstract') 같은 방식이 되겠네요.

2021-04-22 08:13 UTC, hughugh approved these changes

2021-04-22 10:02 UTC, merged